"""day_passes table

Revision ID: 247f4b16757b
Revises: 97f368104092
Create Date: 2026-09-16 20:28:42.262445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '247f4b16757b'
down_revision = '97f368104092'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day_passes',
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('pass_date', sa.Date(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('ISSUED', 'CHECKED_IN', 'CANCELLED', name='daypassstatus'), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('day_passes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_day_passes_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_day_passes_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_day_passes_pass_date'), ['pass_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_day_passes_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_day_passes_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_day_passes_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('day_passes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_day_passes_user_id'))
        batch_op.drop_index(batch_op.f('ix_day_passes_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_day_passes_status'))
        batch_op.drop_index(batch_op.f('ix_day_passes_pass_date'))
        batch_op.drop_index(batch_op.f('ix_day_passes_location_id'))
        batch_op.drop_index(batch_op.f('ix_day_passes_code'))

    op.drop_table('day_passes')
    # ### end Alembic commands ###
