"""phase4: community features

Revision ID: 468c0a7134a7
Revises: e8acfa92bd79
Create Date: 2026-09-16 20:47:56.159525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '468c0a7134a7'
down_revision = 'e8acfa92bd79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_announcements_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcements_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcements_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('community_profiles',
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('headline', sa.String(length=200), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('skills', sa.String(length=500), nullable=True),
    sa.Column('linkedin_url', sa.String(length=300), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('community_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_profiles_is_public'), ['is_public'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_profiles_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('guest_passes',
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('issuer_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('guest_name', sa.String(length=150), nullable=False),
    sa.Column('guest_email', sa.String(length=255), nullable=True),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('ISSUED', 'USED', 'CANCELLED', name='guestpassstatus'), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['issuer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guest_passes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guest_passes_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_guest_passes_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guest_passes_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guest_passes_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_guest_passes_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guest_passes_visit_date'), ['visit_date'], unique=False)

    op.create_table('lockers',
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('monthly_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'ASSIGNED', 'MAINTENANCE', name='lockerstatus'), nullable=False),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lockers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lockers_assigned_user_id'), ['assigned_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lockers_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lockers_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_lockers_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('printing_ledger',
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('printing_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_printing_ledger_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_printing_ledger_user_id'), ['user_id'], unique=False)

    op.create_table('referrals',
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('referrer_id', sa.Integer(), nullable=False),
    sa.Column('referred_email', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('reward_credits', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SIGNED_UP', 'CREDITED', 'EXPIRED', name='referralstatus'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_referrals_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_referrals_referred_email'), ['referred_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_referrals_referrer_id'), ['referrer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_referrals_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_referrals_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('support_tickets',
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('submitter_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='ticketstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='ticketpriority'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitter_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_tickets_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_tickets_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_tickets_submitter_id'), ['submitter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_tickets_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('visitors',
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('host_user_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('company', sa.String(length=150), nullable=True),
    sa.Column('expected_at', sa.DateTime(), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CHECKED_IN', 'CHECKED_OUT', 'CANCELLED', name='visitorstatus'), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(), nullable=True),
    sa.Column('checked_out_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['host_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visitors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visitors_expected_at'), ['expected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_visitors_host_user_id'), ['host_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visitors_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visitors_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_visitors_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visitors_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_visitors_status'))
        batch_op.drop_index(batch_op.f('ix_visitors_location_id'))
        batch_op.drop_index(batch_op.f('ix_visitors_host_user_id'))
        batch_op.drop_index(batch_op.f('ix_visitors_expected_at'))

    op.drop_table('visitors')
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_tickets_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_support_tickets_submitter_id'))
        batch_op.drop_index(batch_op.f('ix_support_tickets_status'))
        batch_op.drop_index(batch_op.f('ix_support_tickets_location_id'))

    op.drop_table('support_tickets')
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referrals_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_referrals_status'))
        batch_op.drop_index(batch_op.f('ix_referrals_referrer_id'))
        batch_op.drop_index(batch_op.f('ix_referrals_referred_email'))
        batch_op.drop_index(batch_op.f('ix_referrals_code'))

    op.drop_table('referrals')
    with op.batch_alter_table('printing_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_printing_ledger_user_id'))
        batch_op.drop_index(batch_op.f('ix_printing_ledger_tenant_id'))

    op.drop_table('printing_ledger')
    with op.batch_alter_table('lockers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lockers_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_lockers_status'))
        batch_op.drop_index(batch_op.f('ix_lockers_location_id'))
        batch_op.drop_index(batch_op.f('ix_lockers_assigned_user_id'))

    op.drop_table('lockers')
    with op.batch_alter_table('guest_passes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guest_passes_visit_date'))
        batch_op.drop_index(batch_op.f('ix_guest_passes_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_guest_passes_status'))
        batch_op.drop_index(batch_op.f('ix_guest_passes_location_id'))
        batch_op.drop_index(batch_op.f('ix_guest_passes_company_id'))
        batch_op.drop_index(batch_op.f('ix_guest_passes_code'))

    op.drop_table('guest_passes')
    with op.batch_alter_table('community_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_community_profiles_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_community_profiles_is_public'))

    op.drop_table('community_profiles')
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_announcements_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_announcements_published_at'))
        batch_op.drop_index(batch_op.f('ix_announcements_location_id'))

    op.drop_table('announcements')
    # ### end Alembic commands ###
