"""initial

Revision ID: 823db404e35a
Revises: 
Create Date: 2026-09-16 18:03:44.405477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '823db404e35a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenities',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('icon', sa.String(length=80), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('companies',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('tax_id', sa.String(length=64), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('billing_email', sa.String(length=255), nullable=False),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('status', sa.Enum('PROSPECT', 'ACTIVE', 'SUSPENDED', 'CHURNED', name='companystatus'), nullable=False),
    sa.Column('max_employees', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_companies_status'), ['status'], unique=False)

    op.create_table('locations',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('state', sa.String(length=80), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('is_247', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pricing_plans',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('plan_type', sa.Enum('HOT_DESK', 'DEDICATED_DESK', 'PRIVATE_OFFICE', 'ALL_ACCESS', 'DAY_PASS', 'CUSTOM', name='plantype'), nullable=False),
    sa.Column('billing_cycle', sa.Enum('DAILY', 'MONTHLY', 'QUARTERLY', 'ANNUAL', name='billingcycle'), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('included_meeting_credits', sa.Integer(), nullable=False),
    sa.Column('included_print_credits', sa.Integer(), nullable=False),
    sa.Column('guest_passes', sa.Integer(), nullable=False),
    sa.Column('max_locations', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('room_amenities',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('location_amenities',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('amenity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'amenity_id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'LOCATION_MANAGER', 'COMPANY_ADMIN', 'EMPLOYEE', 'INDIVIDUAL', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('managed_location_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['managed_location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('documents',
    sa.Column('kind', sa.Enum('CONTRACT', 'KYC', 'INVOICE_PDF', 'FLOOR_MAP', 'COMPANY_LOGO', 'OTHER', name='documentkind'), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('storage_backend', sa.String(length=20), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_kind'), ['kind'], unique=False)

    op.create_table('subscriptions',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'CANCELLED', 'EXPIRED', name='subscriptionstatus'), nullable=False),
    sa.Column('meeting_credits_balance', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(company_id IS NOT NULL) OR (user_id IS NOT NULL)', name='ck_subscription_target_present'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['pricing_plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('company_documents',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('floors',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('map_document_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['map_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ISSUED', 'PAID', 'PARTIAL', 'VOID', 'OVERDUE', name='invoicestatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('pdf_document_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pdf_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_number'), ['number'], unique=True)
        batch_op.create_index(batch_op.f('ix_invoices_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_user_id'), ['user_id'], unique=False)

    op.create_table('conference_rooms',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('credit_cost_per_hour', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'code', name='uq_room_location_code')
    )
    with op.batch_alter_table('conference_rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conference_rooms_floor_id'), ['floor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conference_rooms_location_id'), ['location_id'], unique=False)

    op.create_table('invoice_line_items',
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice_line_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_line_items_invoice_id'), ['invoice_id'], unique=False)

    op.create_table('payments',
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_invoice_id'), ['invoice_id'], unique=False)

    op.create_table('seats',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('seat_type', sa.Enum('HOT_DESK', 'DEDICATED_DESK', 'PRIVATE_OFFICE', name='seattype'), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('daily_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('monthly_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'code', name='uq_seat_location_code')
    )
    with op.batch_alter_table('seats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seats_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_seats_floor_id'), ['floor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seats_location_id'), ['location_id'], unique=False)

    op.create_table('room_amenity_link',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('amenity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['room_amenities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['conference_rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id', 'amenity_id')
    )
    op.create_table('room_bookings',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('CONFIRMED', 'CHECKED_IN', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='bookingstatus'), nullable=False),
    sa.Column('attendee_count', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('credits_used', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['conference_rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('room_bookings', schema=None) as batch_op:
        batch_op.create_index('ix_room_booking_conflict', ['room_id', 'start_at', 'end_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_bookings_end_at'), ['end_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_bookings_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_bookings_start_at'), ['start_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_bookings_user_id'), ['user_id'], unique=False)

    op.create_table('seat_allocations',
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PENDING', 'ENDED', name='allocationstatus'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(company_id IS NOT NULL) OR (user_id IS NOT NULL)', name='ck_allocation_target_present'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seat_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seat_allocations_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seat_allocations_seat_id'), ['seat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seat_allocations_user_id'), ['user_id'], unique=False)

    op.create_table('seat_bookings',
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('CONFIRMED', 'CHECKED_IN', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='bookingstatus'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seat_bookings', schema=None) as batch_op:
        batch_op.create_index('ix_seat_booking_conflict', ['seat_id', 'start_at', 'end_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_seat_bookings_end_at'), ['end_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_seat_bookings_seat_id'), ['seat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seat_bookings_start_at'), ['start_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_seat_bookings_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seat_bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seat_bookings_user_id'))
        batch_op.drop_index(batch_op.f('ix_seat_bookings_start_at'))
        batch_op.drop_index(batch_op.f('ix_seat_bookings_seat_id'))
        batch_op.drop_index(batch_op.f('ix_seat_bookings_end_at'))
        batch_op.drop_index('ix_seat_booking_conflict')

    op.drop_table('seat_bookings')
    with op.batch_alter_table('seat_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seat_allocations_user_id'))
        batch_op.drop_index(batch_op.f('ix_seat_allocations_seat_id'))
        batch_op.drop_index(batch_op.f('ix_seat_allocations_company_id'))

    op.drop_table('seat_allocations')
    with op.batch_alter_table('room_bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_bookings_user_id'))
        batch_op.drop_index(batch_op.f('ix_room_bookings_start_at'))
        batch_op.drop_index(batch_op.f('ix_room_bookings_room_id'))
        batch_op.drop_index(batch_op.f('ix_room_bookings_end_at'))
        batch_op.drop_index('ix_room_booking_conflict')

    op.drop_table('room_bookings')
    op.drop_table('room_amenity_link')
    with op.batch_alter_table('seats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seats_location_id'))
        batch_op.drop_index(batch_op.f('ix_seats_floor_id'))
        batch_op.drop_index(batch_op.f('ix_seats_code'))

    op.drop_table('seats')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_invoice_id'))

    op.drop_table('payments')
    with op.batch_alter_table('invoice_line_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_line_items_invoice_id'))

    op.drop_table('invoice_line_items')
    with op.batch_alter_table('conference_rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conference_rooms_location_id'))
        batch_op.drop_index(batch_op.f('ix_conference_rooms_floor_id'))

    op.drop_table('conference_rooms')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_user_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_status'))
        batch_op.drop_index(batch_op.f('ix_invoices_number'))
        batch_op.drop_index(batch_op.f('ix_invoices_company_id'))

    op.drop_table('invoices')
    op.drop_table('floors')
    op.drop_table('company_documents')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_plan_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_company_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_kind'))

    op.drop_table('documents')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_company_id'))

    op.drop_table('users')
    op.drop_table('location_amenities')
    op.drop_table('room_amenities')
    op.drop_table('pricing_plans')
    op.drop_table('locations')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_status'))
        batch_op.drop_index(batch_op.f('ix_companies_name'))

    op.drop_table('companies')
    op.drop_table('amenities')
    # ### end Alembic commands ###
