"""system settings + INR defaults

Revision ID: bc54cafdfc41
Revises: d0276dfff055
Create Date: 2026-09-16 18:52:31.517164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc54cafdfc41'
down_revision = 'd0276dfff055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('currency_symbol', sa.String(length=4), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('number_grouping', sa.String(length=20), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('date_format', sa.String(length=30), nullable=False),
    sa.Column('datetime_format', sa.String(length=30), nullable=False),
    sa.Column('time_format', sa.String(length=20), nullable=False),
    sa.Column('default_tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_label', sa.String(length=30), nullable=False),
    sa.Column('company_legal_name', sa.String(length=200), nullable=True),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('pan', sa.String(length=20), nullable=True),
    sa.Column('invoice_prefix', sa.String(length=10), nullable=False),
    sa.Column('show_currency_code_after_symbol', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_settings')
    # ### end Alembic commands ###
