"""phase3: 2fa cols + waitlist + recurring bookings

Revision ID: e8acfa92bd79
Revises: 247f4b16757b
Create Date: 2026-09-16 20:40:13.056558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8acfa92bd79'
down_revision = '247f4b16757b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_room_bookings',
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.Enum('DAILY', 'WEEKLY', name='recurrencepattern'), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['conference_rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurring_room_bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring_room_bookings_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurring_room_bookings_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurring_room_bookings_user_id'), ['user_id'], unique=False)

    op.create_table('room_waitlist',
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'NOTIFIED', 'FULFILLED', 'CANCELLED', name='waitliststatus'), nullable=False),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['conference_rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('room_waitlist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_waitlist_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_waitlist_start_at'), ['start_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_waitlist_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_waitlist_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_waitlist_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('two_factor_secret', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('two_factor_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('two_factor_enabled')
        batch_op.drop_column('two_factor_secret')

    with op.batch_alter_table('room_waitlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_waitlist_user_id'))
        batch_op.drop_index(batch_op.f('ix_room_waitlist_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_room_waitlist_status'))
        batch_op.drop_index(batch_op.f('ix_room_waitlist_start_at'))
        batch_op.drop_index(batch_op.f('ix_room_waitlist_room_id'))

    op.drop_table('room_waitlist')
    with op.batch_alter_table('recurring_room_bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_room_bookings_user_id'))
        batch_op.drop_index(batch_op.f('ix_recurring_room_bookings_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_recurring_room_bookings_room_id'))

    op.drop_table('recurring_room_bookings')
    # ### end Alembic commands ###
